<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE refentry PUBLIC "-//OASIS//DTD DocBook XML V4.4//EN"
"http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd">
<refentry id="{@id}">
  <refnamediv>
    <refname>tutorial PapayaQuestionnaireQuestionAbstract</refname>

    <refpurpose>Explains purpose and usage of the abstract question
    class.</refpurpose>
  </refnamediv>

  <refsynopsisdiv>
    <author>papaya Software GmbH</author>
  </refsynopsisdiv>

  <refsect1 id="{@id wlab-questionnaire-group-page}">
    <title>Purpose</title>

    <para>The abstract question class PapayaQuestionnaireQuestionAbstract
    implements shared methods that will be used by most custom question
    modules. If need arises some of those methods may be overridden. This
    makes it simple to implement new question modules with minimum coding
    efford.</para>
  </refsect1>

  <refsect1 id="{@id wlab-questionnaire-group-page}">
    <title>Usage</title>

    <para>@TODO</para>
  </refsect1>
</refentry>
